### ISSUE TITLE
Various errors in the readme

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox-v2-alpha#13]
In the `Readme.md` are several errors reported by Mardown-Lint and some typos.

**Comment by rfelber** [comment]
Maybe we should integrate a markdown-linter into the ci-build to prevent such errors in the feature 🤔

**Comment by J12934** [comment]
> Maybe we should integrate a markdown-linter into the ci-build to prevent such errors in the feature 🤔

We could use the new "super-linter" to lint everything in the project. :)
https://github.com/github/super-linter

**Comment by J12934** [comment]
Also just noticed the helm install instructions still point to the deleted `integrations` folder

**Comment by Weltraumschaf** [comment]
> Also just noticed the helm install instructions still point to the deleted integrations folder

Why is the `hooks` directory in plural but the `scanner` directory in singular?

I recommend `mv scanner scanners` for better coherence.

**Comment by rfelber** [comment]
`mv scanner scanners` sounds valid - make it happen :)
