### ISSUE TITLE
Rename scanner directory

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox-v2-alpha#23]
The directory with the built-in scanners is named in singular. This is not consistent to the rest of the directory layout (tests, hooks etc.) where more than one entities live.

One expects the directory named "scanners".

**Comment by Weltraumschaf** [comment]
Didn't adapt all occurrences of the paths.

**Comment by J12934** [comment]
@Weltraumschaf 
Fixed some leftovers post merge:
f9f1b5999d826daedd592a3745d454d0877ba244
e12ddb7130289e36c84c3b2a6a0af0c99d045441

CI is passing again now.

**Comment by Weltraumschaf** [comment]
@J12934 There were even more leftovers.
