### ISSUE TITLE
There is no Architecutre Picture

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox-v2-alpha#50]
There should be some overview pictures to describe the new k8s based architecture.

**Comment by J12934** [comment]
No architecture picture is inaccurate. Have you seen the diagram in the readme?

See: https://github.com/secureCodeBox/secureCodeBox-v2-alpha#architecture

**Comment by Weltraumschaf** [comment]
> No architecture picture is inaccurate. Have you seen the diagram in the readme?
> 
> See: https://github.com/secureCodeBox/secureCodeBox-v2-alpha#architecture

Yes and it is not appropriate as architecture picture. It is more a marketing picture. What we need is a diagram which shows *all* main components and how the interact/depend with/on each other and shows the main concepts used.
