### ISSUE TITLE
Slack link is no longer active

### ISSUE THREAD

**Issue by MatthReich** [secureCodeBox/secureCodeBox-v2-alpha#92]
When trying to join Slack via [https://github.com/secureCodeBox/secureCodeBox-v2#community](https://github.com/secureCodeBox/secureCodeBox-v2#community) or [https://owasp.org/www-project-securecodebox/](https://owasp.org/www-project-securecodebox/) the Message "This link is no longer active - If you have an email address ending in @iteratec.de or @iteratec.at, you can join this workspace using that address. Otherwise, you’ll need to ask for a new link." appears. Only the Link on [https://www.securecodebox.io/](https://www.securecodebox.io/) works.

**Comment by J12934** [comment]
The darn slack links 😅
Update the two locations, thanks again for pointing it out 🙏
