### ISSUE TITLE
Trigger rebuild of Website build on Reposiory Changes

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox-v2-alpha#99]
**Is your feature request related to a problem? Please describe.**

The website (at the time of writing located a https://docs.securecodebox.io) pulls in files from this repository at its build time.  As the website build is only triggered by changes to the website repository (currently located at: https://github.com/secureCodeBox/docusaurus) changes to this repository will not automatically trigger a rebuild. This can lead to outdated content.

**Describe the solution you'd like**

The build should be triggered when this repository has been updated. (E.g. commits pushed to the master branch)

**Describe alternatives you've considered**

Manually trigger the build by pushing an empty commit to the website repo.

**Additional context**

The website is hosted on netlify.
Current best guess on a potential implementation is to trigger the build using a webhook configured in github (can be configured in the settings of a repository).

**Comment by J12934** [comment]
I think this can only be done by someone with both github admin and netfliy access which means that only @rseedorff can really do it ;)

**Comment by rfelber** [comment]
Done
